import { ScrapedProduct } from "./amazon";
import { AMAZON_FLAGPOLE_URL, AMAZON_OUTDOOR_URL, AMAZON_NUTCRACKER_URL, AMAZON_CHRISTMAS_TREE_URL } from "./constants";
import { createProductSlug } from "./slug";

export const SAMPLE_FEATURED_PRODUCTS: ScrapedProduct[] = [
  {
    asin: "B00FAIRY6M",
    title: "Fairybell LED Kerstboom 6m · 900 LEDs · Warm wit",
    url: "https://www.amazon.nl/Fairybell-LED-Kerstboom-Buiten-Vlaggenmast/dp/B07BB1P585",
    slug: createProductSlug("Fairybell LED Kerstboom 6m · 900 LEDs · Warm wit"),
    price: "€169,95",
    badge: "Bestseller",
    rating: "4,6 van 5 sterren",
    reviews: "106 beoordelingen",
    delivery: "Gratis bezorging 24 - 26 nov",
    image: "/products/fairybell.jpg",
    category: "vlaggenmast",
  },
  {
    asin: "B0CI2BAYCON",
    title: "iBaycon Kerstverlichting vlaggenmast · 12 slingers · 274 LEDs",
    url: "https://www.amazon.nl/s?k=ibaycon+kerstverlichting+vlaggenmast",
    slug: createProductSlug("iBaycon Kerstverlichting vlaggenmast · 12 slingers · 274 LEDs"),
    price: "€49,99",
    badge: "Amazon's Choice",
    rating: "4,5 van 5 sterren",
    reviews: "106 beoordelingen",
    delivery: "Gratis bezorging 2 dec",
    image: "/products/ibaycon.jpg",
    category: "vlaggenmast",
  },
  {
    asin: "B0CVIDAXL1534",
    title: "vidaXL LED vlaggenmast boom · 5m · 1534 LEDs",
    url: "https://www.amazon.nl/s?k=vidaxl+led+vlaggenmast+1534",
    slug: createProductSlug("vidaXL LED vlaggenmast boom · 5m · 1534 LEDs"),
    price: "€86,99",
    badge: "Nieuw",
    rating: "3,5 van 5 sterren",
    reviews: "5 beoordelingen",
    delivery: "Gratis bezorging 19 - 20 nov",
    image: "/products/vidaxl.jpg",
    category: "vlaggenmast",
  },
  {
    asin: "B0LED360",
    title: "Led-lichtketting voor vlaggenmasten · Vlaggenmast · 10 strengen à 8 meter met 360 leds in warm wit",
    url: "https://www.amazon.nl/s?k=led+lichtketting+vlaggenmast+360+leds",
    slug: createProductSlug("Led-lichtketting voor vlaggenmasten · Vlaggenmast · 10 strengen à 8 meter met 360 leds in warm wit"),
    price: "€41,95",
    badge: "Amazon's Choice",
    rating: "4,1 van 5 sterren",
    reviews: "192 beoordelingen",
    delivery: "€ 9,99 bezorging 21 - 24 nov",
    image: "/products/led-lichtketting-360.jpg",
  },
  {
    asin: "B0TIDYARD732",
    title: "Tidyard Kerstboomlichtsnoer · kerstverlichting · kerstversiering · kerstdecoratie buiten · led-lichtketting voor vlaggenmast · warmwit · 732 leds · 500 cm",
    url: "https://www.amazon.nl/s?k=tidyard+kerstboomlichtsnoer+732+leds",
    slug: createProductSlug("Tidyard Kerstboomlichtsnoer · kerstverlichting · kerstversiering · kerstdecoratie buiten · led-lichtketting voor vlaggenmast · warmwit · 732 leds · 500 cm"),
    price: "€70,97",
    badge: null,
    rating: null,
    reviews: null,
    delivery: "GRATIS bezorging 21 - 22 nov",
    image: "/products/tidyard-732.jpg",
  },
  {
    asin: "B0ECD360",
    title: "ECD Germany Vlaggenmast lichtketting · 10 strengen van elk 8 meter met 360 LED's in warm wit voor bomen incl. 10 haringen en 10 kabelbinders zwart IP44 buiten vlaggenmastverlichting buitenverlichting",
    url: "https://www.amazon.nl/s?k=ecd+germany+vlaggenmast+lichtketting+360",
    slug: createProductSlug("ECD Germany Vlaggenmast lichtketting · 10 strengen van elk 8 meter met 360 LED's in warm wit"),
    price: "€49,34",
    badge: null,
    rating: null,
    reviews: null,
    delivery: "GRATIS bezorging 21 - 25 nov",
    image: "/products/ecd-germany-360.jpg",
  },
  {
    asin: "B0GALAXY960",
    title: "Galaxy Led-dennenboom · 600 cm · met 960 warmwitte leds",
    url: "https://www.amazon.nl/s?k=galaxy+led+dennenboom+600+cm+960+leds",
    slug: createProductSlug("Galaxy Led-dennenboom · 600 cm · met 960 warmwitte leds"),
    price: "€159,99",
    badge: null,
    rating: "4,3 van 5 sterren",
    reviews: "9 beoordelingen",
    delivery: "€ 7,99 bezorging 24 - 26 nov",
    image: "/products/galaxy-960.jpg",
  },
  {
    asin: "B0LILENO400",
    title: "LILENO HOME Lichtsnoer voor de kerstboom · vlaggenmast · 800 cm · 400 leds · voor buiten en binnen · led-lichtketting met ring · boommantel · lichtketting als kerstdecoratie · kerstboomversiering",
    url: "https://www.amazon.nl/s?k=lileno+home+lichtsnoer+800+cm+400+leds",
    slug: createProductSlug("LILENO HOME Lichtsnoer voor de kerstboom · vlaggenmast · 800 cm · 400 leds"),
    price: "€44,99",
    badge: null,
    rating: "3,0 van 5 sterren",
    reviews: "1 beoordeling",
    delivery: "GRATIS bezorging 21 - 25 nov",
    image: "/products/lileno-400.jpg",
  },
  {
    asin: "B0MULTISTORE360",
    title: "Multistore 2002 Lichtsnoer voor vlaggenstok · met 360 leds · 10 strengen à 8 m · warm wit licht · vlaggenmastverlichting · kerstdecoratie · ook te gebruiken als kerstboomverlichting",
    url: "https://www.amazon.nl/s?k=multistore+2002+lichtsnoer+360+leds",
    slug: createProductSlug("Multistore 2002 Lichtsnoer voor vlaggenstok · met 360 leds · 10 strengen à 8 m"),
    price: "€41,49",
    badge: null,
    rating: "4,2 van 5 sterren",
    reviews: "556 beoordelingen",
    delivery: null,
    image: "/products/multistore-360.jpg",
  },
  {
    asin: "B0VIDAXL570",
    title: "vidaXL LED-kerstboom met spikes · 570 LEDs kleurrijk · 300 cm · kerstversiering · kerstverlichting · LED-verlichting · kerstverlichting voor buiten · kegelvormige kerstboom",
    url: "https://www.amazon.nl/s?k=vidaxl+led+kerstboom+spikes+570+leds",
    slug: createProductSlug("vidaXL LED-kerstboom met spikes · 570 LEDs kleurrijk · 300 cm"),
    price: "€61,00",
    badge: null,
    rating: "3,6 van 5 sterren",
    reviews: "42 beoordelingen",
    delivery: "GRATIS bezorging 19 - 20 nov",
    image: "/products/vidaxl-spikes-570.jpg",
  },
  {
    asin: "B0RING400",
    title: "Lichtketting kerstboom met ring · 2,5 m · 16 strengen · 400 leds · IP65 waterdicht · voor buiten met 5 m voedingskabel · kerstverlichting binnen · 8 modi · timer voor 150 · 180 of 240 cm · dennenboom · warmwit",
    url: "https://www.amazon.nl/s?k=lichtketting+kerstboom+ring+400+leds",
    slug: createProductSlug("Lichtketting kerstboom met ring · 2,5 m · 16 strengen · 400 leds"),
    price: "€26,99",
    badge: null,
    rating: "4,5 van 5 sterren",
    reviews: "98 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/ring-400.jpg",
  },
  {
    asin: "B0SALCAR280",
    title: "SALCAR 2 m kerstboomverlichting met ring en 8 slingers · 280 led-lampjes · lichtketting voor dennenboom van 150 cm · 180 cm · 210 cm · 240 cm · warm wit",
    url: "https://www.amazon.nl/s?k=salcar+2m+kerstboomverlichting+280+leds",
    slug: createProductSlug("SALCAR 2 m kerstboomverlichting met ring en 8 slingers · 280 led-lampjes"),
    price: "€29,99",
    badge: "Best beoordeeld",
    rating: "4,7 van 5 sterren",
    reviews: "4,9K beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/salcar-280.jpg",
  },
  {
    asin: "B0BUUDALA200",
    title: "Buudala Kerstverlichting voor buiten · 6,4 + 5 m · 200 leds · kerstdecoratie · 8 modi · natuurverlichting · buiten · IP65 · waterdicht · gordijn met timer · geheugenfunctie voor feestjes · bruiloften · tuin · RGB",
    url: "https://www.amazon.nl/s?k=buudala+kerstverlichting+200+leds",
    slug: createProductSlug("Buudala Kerstverlichting voor buiten · 6,4 + 5 m · 200 leds"),
    price: "€28,00",
    badge: null,
    rating: "4,6 van 5 sterren",
    reviews: "3 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/buudala-200.jpg",
  },
  {
    asin: "B0WISHSTAR40",
    title: "Wishstar Sneeuwvlok-lichtsnoer · 6 m · 40 leds · kerstverlichting",
    url: "https://www.amazon.nl/s?k=wishstar+sneeuwvlok+lichtsnoer+40+leds",
    slug: createProductSlug("Wishstar Sneeuwvlok-lichtsnoer · 6 m · 40 leds"),
    price: "€8,53",
    badge: null,
    rating: "4,1 van 5 sterren",
    reviews: "9 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/wishstar-40.jpg",
    category: "vlaggenmast",
  },
];

// Producten van kerstverlichting buiten categorie
export const SAMPLE_OUTDOOR_PRODUCTS: ScrapedProduct[] = [
  {
    asin: "JTSIOV200",
    title: "JTSIOV Kerstverlichting Voor Buiten 20 M 200 Led'S, Kerstboomverlichting met 8 Standen, GeïNtegreerd Geheugen, IP44 Waterdicht",
    url: "https://www.amazon.nl/dp/B0C1234567",
    slug: createProductSlug("JTSIOV Kerstverlichting Voor Buiten 20 M 200 Led'S"),
    price: "€17,99",
    badge: "Bestseller",
    rating: "4,6 van 5 sterren",
    reviews: "41 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/jtsiov-200.jpg",
    category: "buiten",
  },
  {
    asin: "IBAYCON568",
    title: "iBaycon Kerstverlichting voor buiten met ster, 3,87 m x 16 slingers, 568 ledlampen voor kerstboom met afstandsbediening, 8 timermodi, dimbaar, warmwit",
    url: "https://www.amazon.nl/dp/B0C2345678",
    slug: createProductSlug("iBaycon Kerstverlichting voor buiten met ster 568 ledlampen"),
    price: "€69,99",
    badge: "Amazon's Keuze",
    rating: "4,5 van 5 sterren",
    reviews: "106 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/ibaycon-568.jpg",
    category: "buiten",
  },
  {
    asin: "ANMOSSI400",
    title: "Anmossi Kerstverlichting voor Buiten,12m 400 LED Lichtsnoer met Ijspegels,8 Modi Waterdicht Gordijn Lichtketting, Warm Wit",
    url: "https://www.amazon.nl/dp/B0C3456789",
    slug: createProductSlug("Anmossi Kerstverlichting voor Buiten 12m 400 LED Lichtsnoer met Ijspegels"),
    price: "€34,99",
    badge: null,
    rating: "4,6 van 5 sterren",
    reviews: "31 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/anmossi-400.jpg",
    category: "buiten",
  },
  {
    asin: "IBAYCON274",
    title: "iBaycon Kerstverlichting voor buiten met ster, 2,3 m x 12 slingers, 274 ledlampen voor kerstboom met afstandsbediening, 8 modi, timer, dimbaar, warmwit",
    url: "https://www.amazon.nl/dp/B0C4567890",
    slug: createProductSlug("iBaycon Kerstverlichting voor buiten met ster 274 ledlampen"),
    price: "€49,99",
    badge: null,
    rating: "4,5 van 5 sterren",
    reviews: "106 beoordelingen",
    delivery: "GRATIS bezorging di, 2 dec",
    image: "/products/ibaycon-274.jpg",
    category: "buiten",
  },
  {
    asin: "PHILZOPS480",
    title: "PhilzOps IJsregen-lichtsnoer voor buiten, 480 leds, 19 m, lichtgordijn, ijspegels, kerstverlichting, waterdicht, warmwit",
    url: "https://www.amazon.nl/dp/B0C5678901",
    slug: createProductSlug("PhilzOps IJsregen-lichtsnoer voor buiten 480 leds 19 m"),
    price: "€38,99",
    badge: null,
    rating: "4,3 van 5 sterren",
    reviews: "83 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/philzops-480.jpg",
    category: "buiten",
  },
  {
    asin: "OLLNY400",
    title: "Ollny 2.5 m kerstboomverlichting met ring en 16 slingers, 400 led-lampjes, lichtketting voor dennenboom van 150 cm, 180 cm, 210 cm, 240 cm, warm wit",
    url: "https://www.amazon.nl/dp/B0C6789012",
    slug: createProductSlug("Ollny 2.5 m kerstboomverlichting met ring en 16 slingers 400 led-lampjes"),
    price: "€29,99",
    badge: null,
    rating: "4,5 van 5 sterren",
    reviews: "491 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/ollny-400.jpg",
    category: "buiten",
  },
  {
    asin: "ANMOSSI300",
    title: "Anmossi Slimme LED Lichtsnoer,30m 300 LED Kerstverlichting,APP Bediening,Muzieksynchronisatie,IP44 Waterdicht Lichtketting, Warm Wit en Kleur",
    url: "https://www.amazon.nl/dp/B0C7890123",
    slug: createProductSlug("Anmossi Slimme LED Lichtsnoer 30m 300 LED Kerstverlichting APP Bediening"),
    price: "€29,99",
    badge: null,
    rating: "4,5 van 5 sterren",
    reviews: "34 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/anmossi-300.jpg",
    category: "buiten",
  },
  {
    asin: "ISHABAO",
    title: "iShabao Projector Kerstmis buiten, dubbele kop, dynamische led-sneeuwvlokken, sneeuwpop, projector met timer, waterdichte kerstverlichting voor buiten",
    url: "https://www.amazon.nl/dp/B0C8901234",
    slug: createProductSlug("iShabao Projector Kerstmis buiten dubbele kop dynamische led-sneeuwvlokken"),
    price: "€31,04",
    badge: null,
    rating: "4,7 van 5 sterren",
    reviews: "17 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/ishabao.jpg",
    category: "projectoren",
  },
];

// Producten van kerst notenkraker categorie
export const SAMPLE_NUTCRACKER_PRODUCTS: ScrapedProduct[] = [
  {
    asin: "NUTCRACKER001",
    title: "Lights4fun LED Notenkraker Figuur 60 cm, Kerstdecoratie Buiten, Warm Wit, Timer",
    url: "https://www.amazon.nl/dp/B0D1234567",
    slug: createProductSlug("Lights4fun LED Notenkraker Figuur 60 cm Kerstdecoratie Buiten"),
    price: "€49,99",
    badge: "Bestseller",
    rating: "4,5 van 5 sterren",
    reviews: "128 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/notenkraker-60cm.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER002",
    title: "Lights4fun LED Notenkraker Figuur 90 cm, Kerstverlichting Buiten, Warm Wit, Waterdicht",
    url: "https://www.amazon.nl/dp/B0D2345678",
    slug: createProductSlug("Lights4fun LED Notenkraker Figuur 90 cm Kerstverlichting Buiten"),
    price: "€79,99",
    badge: "Amazon's Keuze",
    rating: "4,6 van 5 sterren",
    reviews: "89 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/notenkraker-90cm.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER003",
    title: "Lights4fun LED Notenkraker Set 2 Stuks 60 cm, Kerstdecoratie Buiten, Warm Wit",
    url: "https://www.amazon.nl/dp/B0D3456789",
    slug: createProductSlug("Lights4fun LED Notenkraker Set 2 Stuks 60 cm Kerstdecoratie Buiten"),
    price: "€89,99",
    badge: null,
    rating: "4,4 van 5 sterren",
    reviews: "67 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/notenkraker-set-2.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER004",
    title: "Lights4fun LED Notenkraker Figuur 120 cm, Grote Kerstdecoratie Buiten, Warm Wit, Timer",
    url: "https://www.amazon.nl/dp/B0D4567890",
    slug: createProductSlug("Lights4fun LED Notenkraker Figuur 120 cm Grote Kerstdecoratie Buiten"),
    price: "€129,99",
    badge: null,
    rating: "4,7 van 5 sterren",
    reviews: "45 beoordelingen",
    delivery: "GRATIS bezorging di, 2 dec",
    image: "/products/notenkraker-120cm.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER005",
    title: "Lights4fun LED Notenkraker Figuur 40 cm, Kleine Kerstdecoratie Binnen/Buiten, Warm Wit",
    url: "https://www.amazon.nl/dp/B0D5678901",
    slug: createProductSlug("Lights4fun LED Notenkraker Figuur 40 cm Kleine Kerstdecoratie"),
    price: "€34,99",
    badge: null,
    rating: "4,3 van 5 sterren",
    reviews: "156 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/notenkraker-40cm.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER006",
    title: "Lights4fun LED Notenkraker Figuur 80 cm, Kerstdecoratie Buiten, Warm Wit, IP44 Waterdicht",
    url: "https://www.amazon.nl/dp/B0D6789012",
    slug: createProductSlug("Lights4fun LED Notenkraker Figuur 80 cm Kerstdecoratie Buiten IP44"),
    price: "€69,99",
    badge: null,
    rating: "4,5 van 5 sterren",
    reviews: "92 beoordelingen",
    delivery: "GRATIS bezorging morgen, 18 nov",
    image: "/products/notenkraker-80cm.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER007",
    title: "Lights4fun LED Notenkraker Set 3 Stuks 60 cm, Kerstdecoratie Buiten, Warm Wit, Timer",
    url: "https://www.amazon.nl/dp/B0D7890123",
    slug: createProductSlug("Lights4fun LED Notenkraker Set 3 Stuks 60 cm Kerstdecoratie Buiten"),
    price: "€129,99",
    badge: "Nieuw",
    rating: "4,6 van 5 sterren",
    reviews: "34 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/notenkraker-set-3.jpg",
    category: "notenkraker",
  },
  {
    asin: "NUTCRACKER008",
    title: "Lights4fun LED Notenkraker Figuur 100 cm, Grote Kerstdecoratie Buiten, Warm Wit, Waterdicht",
    url: "https://www.amazon.nl/dp/B0D8901234",
    slug: createProductSlug("Lights4fun LED Notenkraker Figuur 100 cm Grote Kerstdecoratie Buiten"),
    price: "€99,99",
    badge: null,
    rating: "4,4 van 5 sterren",
    reviews: "78 beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/notenkraker-100cm.jpg",
    category: "notenkraker",
  },
];

// Producten van kunstkerstboom categorie
export const SAMPLE_CHRISTMAS_TREE_PRODUCTS: ScrapedProduct[] = [
  {
    asin: "TREE001",
    title: "HOMCOM Kunstkerstboom 2,1 m kerstboom dennenboom 505 takken dichte takken eenvoudig te monteren authentieke kerstboom met metalen standaard",
    url: "https://www.amazon.nl/dp/B0E1234567",
    slug: createProductSlug("HOMCOM Kunstkerstboom 2,1 m kerstboom dennenboom 505 takken"),
    price: "€59,90",
    badge: "Amazon's Keuze",
    rating: "4,8 van 5 sterren",
    reviews: "81 beoordelingen",
    delivery: "GRATIS bezorging 21 - 26 nov",
    image: "/products/homcom-210cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE002",
    title: "Shatchi Kerstboom 120 cm, groen, 230 takjes, dennenboom met metalen standaard",
    url: "https://www.amazon.nl/dp/B0E2345678",
    slug: createProductSlug("Shatchi Kerstboom 120 cm groen 230 takjes dennenboom"),
    price: "€21,99",
    badge: "Bestseller",
    rating: "4,4 van 5 sterren",
    reviews: "2,1K beoordelingen",
    delivery: "GRATIS bezorging 21 - 22 nov",
    image: "/products/shatchi-120cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE003",
    title: "YITAHOME 183 cm kunstmatige kerstboom smal Scotch Pine met afstandsbediening voorverlichte boom met kegels, naalden en warmwitte/veelkleurige 250 led-kleurveranderingsverlichting",
    url: "https://www.amazon.nl/dp/B0E3456789",
    slug: createProductSlug("YITAHOME 183 cm kunstmatige kerstboom smal Scotch Pine met afstandsbediening"),
    price: "€69,99",
    badge: null,
    rating: "5,0 van 5 sterren",
    reviews: "1 beoordeling",
    delivery: "GRATIS bezorging 21 - 24 nov",
    image: "/products/yitahome-183cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE004",
    title: "Premium kunstkerstboom 90cm Levensecht volle takken met houten standaard en opbergtas Kerstboom kunst van Pure Living",
    url: "https://www.amazon.nl/dp/B0E4567890",
    slug: createProductSlug("Premium kunstkerstboom 90cm Levensecht volle takken Pure Living"),
    price: "€59,95",
    badge: null,
    rating: "4,4 van 5 sterren",
    reviews: "3,9K beoordelingen",
    delivery: "GRATIS bezorging vr, 21 nov",
    image: "/products/premium-90cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE005",
    title: "SALCAR kunstkerstboom 180 cm met 580 punten kunstkerstboomparaplu systeem incl. Kerstboomstandaard kerstdecoratie groen 1,8 m",
    url: "https://www.amazon.nl/dp/B0E5678901",
    slug: createProductSlug("SALCAR kunstkerstboom 180 cm met 580 punten kunstkerstboomparaplu systeem"),
    price: "€81,33",
    badge: null,
    rating: "4,4 van 5 sterren",
    reviews: "2,1K beoordelingen",
    delivery: "GRATIS bezorging do, 20 nov",
    image: "/products/salcar-180cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE006",
    title: "YITAHOME Kunstkerstboom 182 cm ca. 880 takken natuurgetrouw dichte takken dennenboom met metalen standaard en klapsysteemframe snelle montage",
    url: "https://www.amazon.nl/dp/B0E6789012",
    slug: createProductSlug("YITAHOME Kunstkerstboom 182 cm ca. 880 takken natuurgetrouw dichte takken"),
    price: "€79,99",
    badge: null,
    rating: "3,8 van 5 sterren",
    reviews: "93 beoordelingen",
    delivery: "GRATIS bezorging 21 - 24 nov",
    image: "/products/yitahome-182cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE007",
    title: "YITAHOME Kunstkerstboom 182 cm voorversierd met sneeuw en 250 ledverlichting 58 dennenappels 58 bessen ca. 818 takken dennenboom met klapsysteem",
    url: "https://www.amazon.nl/dp/B0E7890123",
    slug: createProductSlug("YITAHOME Kunstkerstboom 182 cm voorversierd met sneeuw en 250 ledverlichting"),
    price: "€99,99",
    badge: null,
    rating: "3,7 van 5 sterren",
    reviews: "3 beoordelingen",
    delivery: "GRATIS bezorging 21 - 24 nov",
    image: "/products/yitahome-182cm-sneeuw.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE008",
    title: "YITAHOME Kunstkerstboom 182 cm smal met 200 ledverlichting ca. 700 takjes natuurgetrouwe dennenboom met klapsysteem en metalen standaard",
    url: "https://www.amazon.nl/dp/B0E8901234",
    slug: createProductSlug("YITAHOME Kunstkerstboom 182 cm smal met 200 ledverlichting ca. 700 takjes"),
    price: "€59,99",
    badge: null,
    rating: "4,4 van 5 sterren",
    reviews: "44 beoordelingen",
    delivery: "GRATIS bezorging 21 - 24 nov",
    image: "/products/yitahome-182cm-smal.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE009",
    title: "Aufun Kunstkerstboom dennenboom met verlichting 350 leds warmwit incl. metalen standaard 820 takken pvc-kerstboom voor kerstdecoratie 180 cm sneeuweffect",
    url: "https://www.amazon.nl/dp/B0E9012345",
    slug: createProductSlug("Aufun Kunstkerstboom dennenboom met verlichting 350 leds warmwit 820 takken"),
    price: "€67,49",
    badge: null,
    rating: "3,9 van 5 sterren",
    reviews: "205 beoordelingen",
    delivery: "GRATIS bezorging 21 - 24 nov",
    image: "/products/aufun-180cm.jpg",
    category: "kunstkerstboom",
  },
  {
    asin: "TREE010",
    title: "COSTWAY 180 cm kunstkerstboom dennenboom met klapsysteem kerstboom met 1000 twijgen pvc-naalden kunstboom voor Kerstmis met metalen standaard groen",
    url: "https://www.amazon.nl/dp/B0E0123456",
    slug: createProductSlug("COSTWAY 180 cm kunstkerstboom dennenboom met klapsysteem 1000 twijgen"),
    price: "€52,99",
    badge: null,
    rating: "4,2 van 5 sterren",
    reviews: "41 beoordelingen",
    delivery: "GRATIS bezorging 22 - 26 nov",
    image: "/products/costway-180cm.jpg",
    category: "kunstkerstboom",
  },
];

// Combineer alle producten
export const ALL_SAMPLE_PRODUCTS: ScrapedProduct[] = [
  ...SAMPLE_FEATURED_PRODUCTS.map((p) => ({ ...p, category: p.category || "vlaggenmast" })),
  ...SAMPLE_OUTDOOR_PRODUCTS,
  ...SAMPLE_NUTCRACKER_PRODUCTS,
  ...SAMPLE_CHRISTMAS_TREE_PRODUCTS,
];

export const SAMPLE_SOURCE = AMAZON_FLAGPOLE_URL;

